# Chart Testing configuration for Helm charts
target-branch: main
chart-dirs:
  - helm
chart-repos:
  - jetstack=https://charts.jetstack.io
  - ingress-nginx=https://kubernetes.github.io/ingress-nginx
  - prometheus-community=https://prometheus-community.github.io/helm-charts
  - grafana=https://grafana.github.io/helm-charts
  - bitnami=https://charts.bitnami.com/bitnami

# Validation settings
validate-chart-schema: true
validate-yaml: true
check-version-increment: false  # Disable for now to avoid false positives

# Build and test settings
build-charts: true
install-charts: true
upgrade-charts: true
test-charts: true

# Timeout settings
helm-extra-args: --timeout 600s
timeout: 600s

# Parallel execution
parallel: 2

# Exclude charts that might have issues
excluded-charts: []

# Include specific charts for testing
included-charts: []

# Subchart configuration
subchart-parents: []

# Linting configuration
lint-conf: .github/lintconf.yaml