apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  {{- $type := default "ClusterIP" .Values.service.type }}
  type: {{ $type }}
  {{- with .Values.service.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
