name: Release Charts

on:
  workflow_call:
    inputs:
      helm-version:
        description: 'Helm version to use'
        required: false
        default: '3.18.4'
        type: string

jobs:
  setup:
    uses: ./.github/workflows/setup-environment.yml
    with:
      helm-version: ${{ inputs.helm-version }}

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
